version: "3"

services:
    nginx:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./src:/var/www/html
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php

    php:
      build:
        context: ./docker/php
      volumes: 
        - ./src:/var/www/html
      depends_on:
        - database
        
    database:
      image: mariadb:10.4
      environment:
        MYSQL_DATABASE: database
        MYSQL_ROOT_PASSWORD: secret
